#pragma once
/* XPM */

static xpm_row_t const mario_run_xpm[] = {
  "192 96 14",
  "  4",
  ". 5",
  "X 0",
  "o 7",
  "O 8",
  "+ 9",
  "@ 10",
  "# 11",
  "$ 12",
  "R 13",
  "& 14",
  "* 15",
  "= 16",
  "- 17",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXX....................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....................XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXX....................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....................XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXX....................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....................XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXX....................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....................XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXX....++++$$$$++++++++++++........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....++++$$$$++++++++++++........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....++++$$$$++++++++++++........XXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXX....++++$$$$++++++++++++........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....++++$$$$++++++++++++........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....++++$$$$++++++++++++........XXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXX....++++$$$$++++++++++++........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....++++$$$$++++++++++++........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....++++$$$$++++++++++++........XXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXX....++++$$$$++++++++++++........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....++++$$$$++++++++++++........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....++++$$$$++++++++++++........XXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXX....----$$$$####OOOOOOOO++++++++....XXXXXXXXXXXXXXXXXXXXXXXXXXXX....----$$$$####OOOOOOOO++++++++....XXXXXXXXXXXXXXXXXXXXXXXXXXXX....----$$$$####OOOOOOOO++++++++....XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXX....----$$$$####OOOOOOOO++++++++....XXXXXXXXXXXXXXXXXXXXXXXXXXXX....----$$$$####OOOOOOOO++++++++....XXXXXXXXXXXXXXXXXXXXXXXXXXXX....----$$$$####OOOOOOOO++++++++....XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXX....----$$$$####OOOOOOOO++++++++....XXXXXXXXXXXXXXXXXXXXXXXXXXXX....----$$$$####OOOOOOOO++++++++....XXXXXXXXXXXXXXXXXXXXXXXXXXXX....----$$$$####OOOOOOOO++++++++....XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXX....----$$$$####OOOOOOOO++++++++....XXXXXXXXXXXXXXXXXXXXXXXXXXXX....----$$$$####OOOOOOOO++++++++....XXXXXXXXXXXXXXXXXXXXXXXXXXXX....----$$$$####OOOOOOOO++++++++....XXXXXXXXXXXXXXXX",
  "XXXXXXXX                        OOOOOOOO++++OOOO....XXXXXXXXXXXXXXXXXXXX                        OOOOOOOO++++OOOO....XXXXXXXXXXXXXXXXXXXX                        OOOOOOOO++++OOOO....XXXXXXXXXXXX",
  "XXXXXXXX                        OOOOOOOO++++OOOO....XXXXXXXXXXXXXXXXXXXX                        OOOOOOOO++++OOOO....XXXXXXXXXXXXXXXXXXXX                        OOOOOOOO++++OOOO....XXXXXXXXXXXX",
  "XXXXXXXX                        OOOOOOOO++++OOOO....XXXXXXXXXXXXXXXXXXXX                        OOOOOOOO++++OOOO....XXXXXXXXXXXXXXXXXXXX                        OOOOOOOO++++OOOO....XXXXXXXXXXXX",
  "XXXXXXXX                        OOOOOOOO++++OOOO....XXXXXXXXXXXXXXXXXXXX                        OOOOOOOO++++OOOO....XXXXXXXXXXXXXXXXXXXX                        OOOOOOOO++++OOOO....XXXXXXXXXXXX",
  "XXXX                                    OOOOOOOOOOOO....XXXXXXXXXXXX                                    OOOOOOOOOOOO....XXXXXXXXXXXX                                    OOOOOOOOOOOO....XXXXXXXX",
  "XXXX                                    OOOOOOOOOOOO....XXXXXXXXXXXX                                    OOOOOOOOOOOO....XXXXXXXXXXXX                                    OOOOOOOOOOOO....XXXXXXXX",
  "XXXX                                    OOOOOOOOOOOO....XXXXXXXXXXXX                                    OOOOOOOOOOOO....XXXXXXXXXXXX                                    OOOOOOOOOOOO....XXXXXXXX",
  "XXXX                                    OOOOOOOOOOOO....XXXXXXXXXXXX                                    OOOOOOOOOOOO....XXXXXXXXXXXX                                    OOOOOOOOOOOO....XXXXXXXX",
  "XXXXXXXXXXXXXXXX@@@@    @@@@    @@@@            ====....XXXXXXXXXXXXXXXXXXXXXXXX@@@@    @@@@    @@@@            ====....XXXXXXXXXXXXXXXXXXXXXXXX@@@@    @@@@    @@@@            ====....XXXXXXXX",
  "XXXXXXXXXXXXXXXX@@@@    @@@@    @@@@            ====....XXXXXXXXXXXXXXXXXXXXXXXX@@@@    @@@@    @@@@            ====....XXXXXXXXXXXXXXXXXXXXXXXX@@@@    @@@@    @@@@            ====....XXXXXXXX",
  "XXXXXXXXXXXXXXXX@@@@    @@@@    @@@@            ====....XXXXXXXXXXXXXXXXXXXXXXXX@@@@    @@@@    @@@@            ====....XXXXXXXXXXXXXXXXXXXXXXXX@@@@    @@@@    @@@@            ====....XXXXXXXX",
  "XXXXXXXXXXXXXXXX@@@@    @@@@    @@@@            ====....XXXXXXXXXXXXXXXXXXXXXXXX@@@@    @@@@    @@@@            ====....XXXXXXXXXXXXXXXXXXXXXXXX@@@@    @@@@    @@@@            ====....XXXXXXXX",
  "XXXXXXXXoooooooo====    ====    ====@@@@    ====oooo====....XXXXXXXXXXXXoooooooo====    ====    ====@@@@    ====oooo====....XXXXXXXXXXXXoooooooo====    ====    ====@@@@    ====oooo====....XXXX",
  "XXXXXXXXoooooooo====    ====    ====@@@@    ====oooo====....XXXXXXXXXXXXoooooooo====    ====    ====@@@@    ====oooo====....XXXXXXXXXXXXoooooooo====    ====    ====@@@@    ====oooo====....XXXX",
  "XXXXXXXXoooooooo====    ====    ====@@@@    ====oooo====....XXXXXXXXXXXXoooooooo====    ====    ====@@@@    ====oooo====....XXXXXXXXXXXXoooooooo====    ====    ====@@@@    ====oooo====....XXXX",
  "XXXXXXXXoooooooo====    ====    ====@@@@    ====oooo====....XXXXXXXXXXXXoooooooo====    ====    ====@@@@    ====oooo====....XXXXXXXXXXXXoooooooo====    ====    ====@@@@    ====oooo====....XXXX",
  "XXXXoooo============================        ====oooo@@@@....XXXXXXXXoooo============================        ====oooo@@@@....XXXXXXXXoooo============================        ====oooo@@@@....XXXX",
  "XXXXoooo============================        ====oooo@@@@....XXXXXXXXoooo============================        ====oooo@@@@....XXXXXXXXoooo============================        ====oooo@@@@....XXXX",
  "XXXXoooo============================        ====oooo@@@@....XXXXXXXXoooo============================        ====oooo@@@@....XXXXXXXXoooo============================        ====oooo@@@@....XXXX",
  "XXXXoooo============================        ====oooo@@@@....XXXXXXXXoooo============================        ====oooo@@@@....XXXXXXXXoooo============================        ====oooo@@@@....XXXX",
  "XXXXoooo@@@@@@@@@@@@@@@@@@@@    ========    ====@@@@    ....XXXXXXXXoooo@@@@@@@@@@@@@@@@@@@@    ========    ====@@@@    ....XXXXXXXXoooo@@@@@@@@@@@@@@@@@@@@    ========    ====@@@@    ....XXXX",
  "XXXXoooo@@@@@@@@@@@@@@@@@@@@    ========    ====@@@@    ....XXXXXXXXoooo@@@@@@@@@@@@@@@@@@@@    ========    ====@@@@    ....XXXXXXXXoooo@@@@@@@@@@@@@@@@@@@@    ========    ====@@@@    ....XXXX",
  "XXXXoooo@@@@@@@@@@@@@@@@@@@@    ========    ====@@@@    ....XXXXXXXXoooo@@@@@@@@@@@@@@@@@@@@    ========    ====@@@@    ....XXXXXXXXoooo@@@@@@@@@@@@@@@@@@@@    ========    ====@@@@    ....XXXX",
  "XXXXoooo@@@@@@@@@@@@@@@@@@@@    ========    ====@@@@    ....XXXXXXXXoooo@@@@@@@@@@@@@@@@@@@@    ========    ====@@@@    ....XXXXXXXXoooo@@@@@@@@@@@@@@@@@@@@    ========    ====@@@@    ....XXXX",
  "XXXXXXXX                            ====@@@@@@@@        XXXXXXXXXXXXXXXX                            ====@@@@@@@@        XXXXXXXXXXXXXXXX                            ====@@@@@@@@        XXXXXXXX",
  "XXXXXXXX                            ====@@@@@@@@        XXXXXXXXXXXXXXXX                            ====@@@@@@@@        XXXXXXXXXXXXXXXX                            ====@@@@@@@@        XXXXXXXX",
  "XXXXXXXX                            ====@@@@@@@@        XXXXXXXXXXXXXXXX                            ====@@@@@@@@        XXXXXXXXXXXXXXXX                            ====@@@@@@@@        XXXXXXXX",
  "XXXXXXXX                            ====@@@@@@@@        XXXXXXXXXXXXXXXX                            ====@@@@@@@@        XXXXXXXXXXXXXXXX                            ====@@@@@@@@        XXXXXXXX",
  "XXXXXXXXXXXX                @@@@@@@@@@@@ooooooooooooooooooooooooXXXXXXXXXXXX                @@@@@@@@@@@@ooooooooooooooooooooooooXXXXXXXXXXXX                @@@@@@@@@@@@oooooooooooooooooooooooo",
  "XXXXXXXXXXXX                @@@@@@@@@@@@ooooooooooooooooooooooooXXXXXXXXXXXX                @@@@@@@@@@@@ooooooooooooooooooooooooXXXXXXXXXXXX                @@@@@@@@@@@@oooooooooooooooooooooooo",
  "XXXXXXXXXXXX                @@@@@@@@@@@@ooooooooooooooooooooooooXXXXXXXXXXXX                @@@@@@@@@@@@ooooooooooooooooooooooooXXXXXXXXXXXX                @@@@@@@@@@@@oooooooooooooooooooooooo",
  "XXXXXXXXXXXX                @@@@@@@@@@@@ooooooooooooooooooooooooXXXXXXXXXXXX                @@@@@@@@@@@@ooooooooooooooooooooooooXXXXXXXXXXXX                @@@@@@@@@@@@oooooooooooooooooooooooo",
  "XXXXXXXXXXXXXXXXXXXXRRRRoooooooooooooooo++++oooo------------ooooXXXXXXXXXXXXXXXXXXXXRRRRoooooooooooooooo++++oooo------------ooooXXXXXXXXXXXXXXXXXXXXRRRRoooooooooooooooo++++oooo------------oooo",
  "XXXXXXXXXXXXXXXXXXXXRRRRoooooooooooooooo++++oooo------------ooooXXXXXXXXXXXXXXXXXXXXRRRRoooooooooooooooo++++oooo------------ooooXXXXXXXXXXXXXXXXXXXXRRRRoooooooooooooooo++++oooo------------oooo",
  "XXXXXXXXXXXXXXXXXXXXRRRRoooooooooooooooo++++oooo------------ooooXXXXXXXXXXXXXXXXXXXXRRRRoooooooooooooooo++++oooo------------ooooXXXXXXXXXXXXXXXXXXXXRRRRoooooooooooooooo++++oooo------------oooo",
  "XXXXXXXXXXXXXXXXXXXXRRRRoooooooooooooooo++++oooo------------ooooXXXXXXXXXXXXXXXXXXXXRRRRoooooooooooooooo++++oooo------------ooooXXXXXXXXXXXXXXXXXXXXRRRRoooooooooooooooo++++oooo------------oooo",
  "XXXXXXXXXXXXXXXXRRRR********&&&&&&&&++++++++oooo--------ooooXXXXXXXXXXXXXXXXXXXXRRRR********&&&&&&&&++++++++oooo--------ooooXXXXXXXXXXXXXXXXXXXXRRRR********&&&&&&&&++++++++oooo--------ooooXXXX",
  "XXXXXXXXXXXXXXXXRRRR********&&&&&&&&++++++++oooo--------ooooXXXXXXXXXXXXXXXXXXXXRRRR********&&&&&&&&++++++++oooo--------ooooXXXXXXXXXXXXXXXXXXXXRRRR********&&&&&&&&++++++++oooo--------ooooXXXX",
  "XXXXXXXXXXXXXXXXRRRR********&&&&&&&&++++++++oooo--------ooooXXXXXXXXXXXXXXXXXXXXRRRR********&&&&&&&&++++++++oooo--------ooooXXXXXXXXXXXXXXXXXXXXRRRR********&&&&&&&&++++++++oooo--------ooooXXXX",
  "XXXXXXXXXXXXXXXXRRRR********&&&&&&&&++++++++oooo--------ooooXXXXXXXXXXXXXXXXXXXXRRRR********&&&&&&&&++++++++oooo--------ooooXXXXXXXXXXXXXXXXXXXXRRRR********&&&&&&&&++++++++oooo--------ooooXXXX",
  "XXXX        RRRR----****--------&&&&&&&&OOOOOOOOoooo    XXXXXXXXXXXX        RRRR----****--------&&&&&&&&OOOOOOOOoooo    XXXXXXXXXXXXXXXXXXXXRRRR----****--------&&&&&&&&OOOOOOOOooooooooXXXXXXXX",
  "XXXX        RRRR----****--------&&&&&&&&OOOOOOOOoooo    XXXXXXXXXXXX        RRRR----****--------&&&&&&&&OOOOOOOOoooo    XXXXXXXXXXXXXXXXXXXXRRRR----****--------&&&&&&&&OOOOOOOOooooooooXXXXXXXX",
  "XXXX        RRRR----****--------&&&&&&&&OOOOOOOOoooo    XXXXXXXXXXXX        RRRR----****--------&&&&&&&&OOOOOOOOoooo    XXXXXXXXXXXXXXXXXXXXRRRR----****--------&&&&&&&&OOOOOOOOooooooooXXXXXXXX",
  "XXXX        RRRR----****--------&&&&&&&&OOOOOOOOoooo    XXXXXXXXXXXX        RRRR----****--------&&&&&&&&OOOOOOOOoooo    XXXXXXXXXXXXXXXXXXXXRRRR----****--------&&&&&&&&OOOOOOOOooooooooXXXXXXXX",
  "        $$$$    ----****--------&&&&&&&&&&&&&&&&oooooooo    XXXX        $$$$    ----****--------&&&&&&&&&&&&&&&&oooooooo    XXXXXXXXXXXXXXXXRRRR----****--------&&&&&&&&&&&&&&&&RRRRXXXXXXXXXXXX",
  "        $$$$    ----****--------&&&&&&&&&&&&&&&&oooooooo    XXXX        $$$$    ----****--------&&&&&&&&&&&&&&&&oooooooo    XXXXXXXXXXXXXXXXRRRR----****--------&&&&&&&&&&&&&&&&RRRRXXXXXXXXXXXX",
  "        $$$$    ----****--------&&&&&&&&&&&&&&&&oooooooo    XXXX        $$$$    ----****--------&&&&&&&&&&&&&&&&oooooooo    XXXXXXXXXXXXXXXXRRRR----****--------&&&&&&&&&&&&&&&&RRRRXXXXXXXXXXXX",
  "        $$$$    ----****--------&&&&&&&&&&&&&&&&oooooooo    XXXX        $$$$    ----****--------&&&&&&&&&&&&&&&&oooooooo    XXXXXXXXXXXXXXXXRRRR----****--------&&&&&&&&&&&&&&&&RRRRXXXXXXXXXXXX",
  "        oooo    RRRR****&&&&&&&&&&&&&&&&&&&&&&&&oooooooo    XXXX        oooo    RRRR****&&&&&&&&&&&&&&&&&&&&&&&&oooooooo    XXXXXXXXXXXXXXXXRRRR********&&&&&&&&&&&&&&&&&&&&&&&&RRRRXXXXXXXXXXXX",
  "        oooo    RRRR****&&&&&&&&&&&&&&&&&&&&&&&&oooooooo    XXXX        oooo    RRRR****&&&&&&&&&&&&&&&&&&&&&&&&oooooooo    XXXXXXXXXXXXXXXXRRRR********&&&&&&&&&&&&&&&&&&&&&&&&RRRRXXXXXXXXXXXX",
  "        oooo    RRRR****&&&&&&&&&&&&&&&&&&&&&&&&oooooooo    XXXX        oooo    RRRR****&&&&&&&&&&&&&&&&&&&&&&&&oooooooo    XXXXXXXXXXXXXXXXRRRR********&&&&&&&&&&&&&&&&&&&&&&&&RRRRXXXXXXXXXXXX",
  "        oooo    RRRR****&&&&&&&&&&&&&&&&&&&&&&&&oooooooo    XXXX        oooo    RRRR****&&&&&&&&&&&&&&&&&&&&&&&&oooooooo    XXXXXXXXXXXXXXXXRRRR********&&&&&&&&&&&&&&&&&&&&&&&&RRRRXXXXXXXXXXXX",
  "XXXX        oooo    RRRR&&&&&&&&&&&&&&&&RRRRRRRRRRRRoooo    XXXXXXXX        oooo    RRRR&&&&&&&&&&&&&&&&RRRRRRRRRRRRoooo    XXXXXXXXXXXXXXXXXXXXRRRR&&&&RRRR&&&&&&&&&&&&&&&&RRRRRRRRXXXXXXXXXXXX",
  "XXXX        oooo    RRRR&&&&&&&&&&&&&&&&RRRRRRRRRRRRoooo    XXXXXXXX        oooo    RRRR&&&&&&&&&&&&&&&&RRRRRRRRRRRRoooo    XXXXXXXXXXXXXXXXXXXXRRRR&&&&RRRR&&&&&&&&&&&&&&&&RRRRRRRRXXXXXXXXXXXX",
  "XXXX        oooo    RRRR&&&&&&&&&&&&&&&&RRRRRRRRRRRRoooo    XXXXXXXX        oooo    RRRR&&&&&&&&&&&&&&&&RRRRRRRRRRRRoooo    XXXXXXXXXXXXXXXXXXXXRRRR&&&&RRRR&&&&&&&&&&&&&&&&RRRRRRRRXXXXXXXXXXXX",
  "XXXX        oooo    RRRR&&&&&&&&&&&&&&&&RRRRRRRRRRRRoooo    XXXXXXXX        oooo    RRRR&&&&&&&&&&&&&&&&RRRRRRRRRRRRoooo    XXXXXXXXXXXXXXXXXXXXRRRR&&&&RRRR&&&&&&&&&&&&&&&&RRRRRRRRXXXXXXXXXXXX",
  "XXXX        oooo    XXXXRRRRRRRRRRRRRRRRXXXX    $$$$oooo    XXXXXXXX        oooo    XXXXRRRRRRRRRRRRRRRRXXXX    $$$$oooo    XXXXXXXXXXXXXXXXXXXXXXXX    oooo    ooooooooooooooooXXXXXXXXXXXXXXXX",
  "XXXX        oooo    XXXXRRRRRRRRRRRRRRRRXXXX    $$$$oooo    XXXXXXXX        oooo    XXXXRRRRRRRRRRRRRRRRXXXX    $$$$oooo    XXXXXXXXXXXXXXXXXXXXXXXX    oooo    ooooooooooooooooXXXXXXXXXXXXXXXX",
  "XXXX        oooo    XXXXRRRRRRRRRRRRRRRRXXXX    $$$$oooo    XXXXXXXX        oooo    XXXXRRRRRRRRRRRRRRRRXXXX    $$$$oooo    XXXXXXXXXXXXXXXXXXXXXXXX    oooo    ooooooooooooooooXXXXXXXXXXXXXXXX",
  "XXXX        oooo    XXXXRRRRRRRRRRRRRRRRXXXX    $$$$oooo    XXXXXXXX        oooo    XXXXRRRRRRRRRRRRRRRRXXXX    $$$$oooo    XXXXXXXXXXXXXXXXXXXXXXXX    oooo    ooooooooooooooooXXXXXXXXXXXXXXXX",
  "XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXX    $$$$    $$$$oooooooooooo    XXXXXXXXXXXXXXXX",
  "XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXX    $$$$    $$$$oooooooooooo    XXXXXXXXXXXXXXXX",
  "XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXX    $$$$    $$$$oooooooooooo    XXXXXXXXXXXXXXXX",
  "XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXX    $$$$    $$$$oooooooooooo    XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX"};




