#pragma once

static xpm_row_t const mouse_xpm[]  = {
"58 42 3",
"  99",
". 63",
"X 0",
"          ....                    ..                      ",
"          ....                    ..                      ",
"        ..XXXX..                  ....                    ",
"        ..XXXX..                  ....                    ",
"        ..XXXX..                  ..XX..                  ",
"        ..XXXX..                  ..XX..                  ",
"        ..XXXX..                  ..XXXX..                ",
"        ..XXXX..                  ..XXXX..                ",
"        ..XXXX..                  ..XXXXXX..              ",
"        ..XXXX......              ..XXXXXX..              ",
"        ..XXXX......              ..XXXXXXXX..            ",
"        ..XXXX..XXXX......        ..XXXXXXXX..            ",
"        ..XXXX..XXXX......        ..XXXXXXXXXX..          ",
"        ..XXXX..XXXX..XXXX....    ..XXXXXXXXXX..          ",
"        ..XXXX..XXXX..XXXX....    ..XXXXXXXXXXXX..        ",
"        ..XXXX..XXXX..XXXX..XX..  ..XXXXXXXXXXXX..        ",
"        ..XXXX..XXXX..XXXX..XX..  ..XXXXXXXXXXXXXX..      ",
"......  ..XXXX..XXXX..XXXX..XXXX....XXXXXXXXXXXXXX..      ",
"......  ..XXXX..XXXX..XXXX..XXXX....XXXXXXXXXXXXXXXX..    ",
"..XXXX....XXXXXXXXXXXXXXXX..XXXX....XXXXXXXXXXXXXXXX..    ",
"..XXXX....XXXXXXXXXXXXXXXX..XXXX....XXXXXXXXXXXXXXXXXX..  ",
"..XXXXXX..XXXXXXXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXX..  ",
"..XXXXXX..XXXXXXXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXX..",
"  ..XXXXXXXXXXXXXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXX..",
"  ..XXXXXXXXXXXXXXXXXXXXXXXXXXXX....XXXXXXXXXXXX..........",
"    ..XXXXXXXXXXXXXXXXXXXXXXXXXX....XXXXXXXXXXXX..........",
"    ..XXXXXXXXXXXXXXXXXXXXXXXXXX....XXXXXX..XXXX..        ",
"    ..XXXXXXXXXXXXXXXXXXXXXXXXXX....XXXXXX..XXXX..        ",
"    ..XXXXXXXXXXXXXXXXXXXXXXXXXX....XXXX..  ..XXXX..      ",
"      ..XXXXXXXXXXXXXXXXXXXXXXXX....XXXX..  ..XXXX..      ",
"      ..XXXXXXXXXXXXXXXXXXXXXX..  ..XX..    ..XXXX..      ",
"      ..XXXXXXXXXXXXXXXXXXXXXX..  ..XX..    ..XXXX..      ",
"      ..XXXXXXXXXXXXXXXXXXXXXX..  ....        ..XXXX..    ",
"        ..XXXXXXXXXXXXXXXXXXXX..  ....        ..XXXX..    ",
"        ..XXXXXXXXXXXXXXXXXXXX..              ..XXXX..    ",
"        ..XXXXXXXXXXXXXXXXXXXX..              ..XXXX..    ",
"        ..XXXXXXXXXXXXXXXXXX..                  ....      ",
"          ..XXXXXXXXXXXXXXXX..                  ....      ",
"          ..XXXXXXXXXXXXXXXX..                            ",
"          ..XXXXXXXXXXXXXXXX..                            ",
"          ....................                            ",
"          ....................                            "
};
